# user variables
name: 'Book of Topaz'
desc: 'I like to recommend a lot of different programs, apps, and tricks to my friends. But now I want to share it with everyone. It is not a typical review/advert as it will provide more subjective experiences.'
author:
  name: Nanosmasher
  avatar: 'https://identicons.github.com/nanosmasher.png'
  profile: 'Learning about games, shows, and life from top-down and from bottom-up.
  (py/lua, smash/PM/FGC, RWBY, blogs, materials engineering)'
  socials:
    twitter: 'https://twitter.com/CrossPunishVG'
    github-alt: 'https://github.com/nanosmasher'
    steam: 'https://steamcommunity.com/id/nanosmasher/'

# site variables
gems: ['jekyll-paginate']
baseurl: /book-of-topaz
paginate: 5
permalink: '/:categories/:title/'
paginate_path: page/:num
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed