# user variables, change this to make custom site.

name: 'Book of Topaz'
desc: 'I like to recommend a lot of different programs, apps, and tricks to my friends. Why stop there? This blog is an assortment of everything I have gathered to share with everyone who stumbles in here.'
author:
  name: Nanosmasher
  avatar: 'https://identicons.github.com/nanosmasher.png'
  profile: 'Learning about games, shows, and life from top-down and from bottom-up.
  (py/lua, smash/PM/FGC, RWBY, blogs, materials engineering)'
  socials:
    twitter: 'https://twitter.com/CrossPunishVG'
    github-alt: 'https://github.com/nanosmasher'
    steam: 'https://steamcommunity.com/id/nanosmasher/'
gems: ['jekyll-paginate']

# theme variables, change this to make site looks best.
baseurl: /book-of-topaz
paginate: 2
permalink: '/:categories/:title/'

# system variables, do not change unless you knew what's it does.
paginate_path: page/:num
highlighter: pygments
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed
